db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"

web:
#  image: ryanfox1985/ylosix
  build: .
  command: bin/rails server --port 3000 --binding 0.0.0.0
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    SECRET_KEY_BASE: <%= rake secret %>
  volumes:
   - tmp/docker/system:/var/www/public/system
