sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

postgresql: &postgresql
  adapter: postgresql
  min_messages: ERROR
  reconnect: false

default: &default
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *postgresql

development:
  url: postgres://ecommerce_user:ecommerce_pass@localhost:5432/ecommerce
  <<: *default

test:
  url: postgres://ecommerce_user:ecommerce_pass@localhost:5432/ecommerce_test
  <<: *default

# Example URL => postgres://pgusername@localhost/development_db
production:
  url: <%= ENV['DATABASE_URL'] %>
  <<: *default
